name: cooking_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  json: ^0.20.2
  mongo_dart: ^0.10.3
  provider: ^6.1.2
  image_picker: ^0.8.4+8

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/HotBar/Gorrito.png
    - assets/Background.png
    - .env
