name: cooking_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  json: ^0.20.2
  provider: ^6.1.2
  
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

  mongo_dart: ^0.10.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Gorrito.png"

flutter:
  uses-material-design: true

  #Imagenes
  assets:
    - assets/HotBar/Gorrito.png
    - assets/HotBar/Games.png
    - assets/HotBar/Lista.png
    - assets/HotBar/Perfil.png
    - assets/HotBar/Home.png
    
    - assets/Background.png
    - assets/HotCakes.png
    - assets/Arepas.png

    - assets/chatIcons/camera.png
    - assets/chatIcons/adjuntar.png
    
    - assets/icons/chat.png
    - assets/icons/camera.png
    - assets/icons/eat.png
    - assets/icons/edit.png
    - assets/icons/edit2.png
    - assets/icons/canasta.png
    - assets/icons/star.png
    - assets/icons/delete.png
  fonts:
    - family : Poppins
      fonts :
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
