// ESTE ARCHIVO CONTENDRA EL LINK PARA LA CONEXION A LA BASE DE DATOS, ASI COMO
// A LAS COLECCIONES A LAS QUE SE QUIERE INGRESAR
//SI QUERE INGRESAR A UNA NUEVA COLECCION CREELA EN ESTE ARCHIVO

const CONNECTIONDB = ""; //Link de conexion a a base de datos
const COLLECTIONINGREDIENTS = "Users"; //Colleccion a la que se quiere acceder
